version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: student_analytics_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "9963"
      MYSQL_DATABASE: "studentanalyticdashboard"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p9963"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: student_analytics_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:9963@mysql:3306/studentanalyticdashboard"
    ports:
      - "8501:8501"
    volumes:
      - ./:/app

volumes:
  mysql_data:

